### ISSUE TITLE
Bootstrap and JQ are needed

### ISSUE THREAD

**Issue by fefo-p** [tattersoftware/codeigniter4-alerts#3]
I think it's necessary to include somewhere in the docs (or the main readme file) that Bootstrap and dependencies are needed for it to work smoothly (ie: colors, correct location and dismisal).

**Comment by MGatner** [comment]
The bottom of the ReadMe states "By default alerts will be displayed with classes for Bootstrap. Styles can be changed to other toolkits (or you may use your own) by altering the settings in the config file." Did you read that and find it unclear? Or not notice it? Do you have suggestions for improved wording that would have helped you?

**Comment by fefo-p** [comment]
oops, sorry. Missed that! :)

Maybe something like this?
**### Styles**
By default, alerts are set to use **Bootstrap** clases (`must already be installed`). 
However, styles can be set to use other toolkits (or you may use your own) by changing the template in the config file.

**Comment by fefo-p** [comment]
And maybe add into Quick Start a reminder that bootstrap should be installed already.
Otherwise, first impression might not be the one we hope for :)

**Comment by fefo-p** [comment]
This image linked show CI4's welcome page (out of the box) with alerts.
[https://pasteboard.co/IyU8QKT.png](https://pasteboard.co/IyU8QKT.png)

**Comment by MGatner** [comment]
Thanks for the suggestions - I updated the README in both places to make it more clear. Ref. 9511233

**Comment by MGatner** [comment]
That's great! May I use your screenshot in place of the current one?

**Comment by fefo-p** [comment]
Sure!

**Comment by fefo-p** [comment]
![alerts](https://user-images.githubusercontent.com/42467872/65525158-725afd00-dec5-11e9-9a57-5225dd599ded.png)

**Comment by MGatner** [comment]
Closed via https://github.com/tattersoftware/codeigniter4-alerts/commit/1c2ed521ed28ac11de091e6934328de980204be2
