### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by paul45** [tattersoftware/codeigniter4-alerts#8]
Hello

this library requierd php 7.3 and not php 7.2 
is there a reason for that ?

Thx

**Comment by MGatner** [comment]
My modules all follow the framework requirements, which currently (`4.1` and `develop`) require 7.3+. If someone needs 7.2 support and wants to champion maintaining it I am open but I have too much on my plate to be in charge of maintaining multiple versioned branches of all my modules. Off the top of my head nothing about the module itself is incompatible with 7.2

**Comment by paul45** [comment]
ok thx for this quick answer
